---

- name: Install prometheus
  package:
    name: prometheus

- name: Install prometheus-node-exporter
  package:
    name: prometheus-node-exporter

# - name: Install prometheus-alertmanager
#   package:
#     name: prometheus-alertmanager-y

- name: Install prometheus-pushgateway
  package:
    name: prometheus-pushgateway


