---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ deployment_name }}"
  name: "{{ service_name }}"
  namespace: default
  resourceVersion: "8778"
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: "{{ deployment_name }}"
  sessionAffinity: None
  type: LoadBalancer