---

- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Join to Kubernetes cluster
  when: reset_cluster is succeeded
  # shell: "kubeadm join --token {{ token }} --discovery-token-ca-cert-hash sha256:69e6eb6b43f9b0c1a8e6a3b7e0643ecdfcf8f4104e8f5adc97d4455bae6d82bf {{ master_ip }}:{{ kube_port }}"
  shell: "kubeadm join --token {{ token }} -–discovery-token-unsafe-skip-ca-verification {{ master_ip }}:{{ kube_port }}"
  register: join_cluster
  notify:
    - Recreate kube-dns
# --discovery-file /etc/kubernetes/kubelet.conf \